version: '3'
services:

  app:
    build: ./docker/app
    volumes:
      - "./:/var/www"
      - "./docker/app/supervisor/:/etc/supervisor/conf.d/:ro"
    depends_on:
      - mysql
    expose:
      - '9000'

  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
